# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DemoApp_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DemoApp(object):
    def setupUi(self, DemoApp):
        DemoApp.setObjectName("DemoApp")
        DemoApp.resize(700, 450)
        self.tabWidget = QtWidgets.QTabWidget(DemoApp)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 681, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 651, 121))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 25, 621, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.outputFolderLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.outputFolderLineEdit.setObjectName("outputFolderLineEdit")
        self.gridLayout.addWidget(self.outputFolderLineEdit, 1, 1, 1, 1)
        self.inputFolderLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inputFolderLineEdit.setObjectName("inputFolderLineEdit")
        self.gridLayout.addWidget(self.inputFolderLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.configFileLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.configFileLineEdit.setObjectName("configFileLineEdit")
        self.gridLayout.addWidget(self.configFileLineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.selectInputFolderPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectInputFolderPushButton.setObjectName("selectInputFolderPushButton")
        self.gridLayout.addWidget(self.selectInputFolderPushButton, 0, 2, 1, 1)
        self.selectOutputFolderPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectOutputFolderPushButton.setObjectName("selectOutputFolderPushButton")
        self.gridLayout.addWidget(self.selectOutputFolderPushButton, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 351, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(15, 25, 321, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.gridLayoutWidget_2.raise_()
        self.label_4.raise_()
        self.label_4.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.analyzerStateLabel = QtWidgets.QLabel(DemoApp)
        self.analyzerStateLabel.setGeometry(QtCore.QRect(20, 420, 50, 12))
        self.analyzerStateLabel.setObjectName("analyzerStateLabel")
        self.progressBar = QtWidgets.QProgressBar(DemoApp)
        self.progressBar.setGeometry(QtCore.QRect(70, 414, 191, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.mainPushButton = QtWidgets.QPushButton(DemoApp)
        self.mainPushButton.setGeometry(QtCore.QRect(290, 410, 121, 31))
        self.mainPushButton.setObjectName("mainPushButton")
        self.readConfigFilePushButton = QtWidgets.QPushButton(DemoApp)
        self.readConfigFilePushButton.setGeometry(QtCore.QRect(430, 410, 121, 31))
        self.readConfigFilePushButton.setObjectName("readConfigFilePushButton")
        self.writeConfigFilePushButton = QtWidgets.QPushButton(DemoApp)
        self.writeConfigFilePushButton.setGeometry(QtCore.QRect(570, 410, 121, 31))
        self.writeConfigFilePushButton.setObjectName("writeConfigFilePushButton")

        self.retranslateUi(DemoApp)
        self.tabWidget.setCurrentIndex(0)
        self.mainPushButton.clicked.connect(DemoApp.multiThread_runMainAnalysis)
        self.selectInputFolderPushButton.clicked.connect(DemoApp.showInputFolderDialog)
        self.selectOutputFolderPushButton.clicked.connect(DemoApp.showOutputFolderDialog)
        self.readConfigFilePushButton.clicked.connect(DemoApp.readConfigFileDialog)
        self.writeConfigFilePushButton.clicked.connect(DemoApp.writeConfigFileDialog)
        QtCore.QMetaObject.connectSlotsByName(DemoApp)

    def retranslateUi(self, DemoApp):
        _translate = QtCore.QCoreApplication.translate
        DemoApp.setWindowTitle(_translate("DemoApp", "DemoApp"))
        self.groupBox.setTitle(_translate("DemoApp", "ファイル関係"))
        self.outputFolderLineEdit.setText(_translate("DemoApp", "入力フォルダの絶対パスを指定してください"))
        self.inputFolderLineEdit.setText(_translate("DemoApp", "入力フォルダの絶対パスを指定してください"))
        self.label_2.setText(_translate("DemoApp", "出力フォルダ"))
        self.label_3.setText(_translate("DemoApp", "Configファイル"))
        self.configFileLineEdit.setText(_translate("DemoApp", "入力フォルダの絶対パスを指定してください"))
        self.label.setText(_translate("DemoApp", "入力フォルダ"))
        self.selectInputFolderPushButton.setText(_translate("DemoApp", "入力フォルダを指定"))
        self.selectOutputFolderPushButton.setText(_translate("DemoApp", "出力フォルダを指定"))
        self.groupBox_2.setTitle(_translate("DemoApp", "データ取得日・測定回数"))
        self.label_4.setText(_translate("DemoApp", "データ取得日(西暦表示)"))
        self.label_5.setText(_translate("DemoApp", "測定回数"))
        self.lineEdit_4.setText(_translate("DemoApp", "001"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DemoApp", "Main処理"))
        self.analyzerStateLabel.setText(_translate("DemoApp", "待機中"))
        self.mainPushButton.setText(_translate("DemoApp", "実行"))
        self.readConfigFilePushButton.setText(_translate("DemoApp", "Configから読込む"))
        self.writeConfigFilePushButton.setText(_translate("DemoApp", "Configへ書込む"))

