# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DemoApp_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DemoApp(object):
    def setupUi(self, DemoApp):
        DemoApp.setObjectName("DemoApp")
        DemoApp.resize(750, 450)
        self.tabWidget = QtWidgets.QTabWidget(DemoApp)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 731, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 711, 131))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 25, 681, 96))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.outputFolderLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.outputFolderLineEdit.setObjectName("outputFolderLineEdit")
        self.gridLayout.addWidget(self.outputFolderLineEdit, 1, 1, 1, 1)
        self.inputFolderLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inputFolderLineEdit.setObjectName("inputFolderLineEdit")
        self.gridLayout.addWidget(self.inputFolderLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.configFileLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.configFileLineEdit.setObjectName("configFileLineEdit")
        self.gridLayout.addWidget(self.configFileLineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.selectInputFolderPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectInputFolderPushButton.setObjectName("selectInputFolderPushButton")
        self.gridLayout.addWidget(self.selectInputFolderPushButton, 0, 2, 1, 1)
        self.selectOutputFolderPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectOutputFolderPushButton.setObjectName("selectOutputFolderPushButton")
        self.gridLayout.addWidget(self.selectOutputFolderPushButton, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 191, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(15, 30, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.valueErrorCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.valueErrorCheckBox.setObjectName("valueErrorCheckBox")
        self.verticalLayout.addWidget(self.valueErrorCheckBox)
        self.fileNotFoundErrorCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fileNotFoundErrorCheckBox.setObjectName("fileNotFoundErrorCheckBox")
        self.verticalLayout.addWidget(self.fileNotFoundErrorCheckBox)
        self.permissionErrorCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.permissionErrorCheckBox.setObjectName("permissionErrorCheckBox")
        self.verticalLayout.addWidget(self.permissionErrorCheckBox)
        self.tabWidget.addTab(self.tab, "")
        self.analyzerStateLabel = QtWidgets.QLabel(DemoApp)
        self.analyzerStateLabel.setGeometry(QtCore.QRect(15, 420, 50, 12))
        self.analyzerStateLabel.setObjectName("analyzerStateLabel")
        self.progressBar = QtWidgets.QProgressBar(DemoApp)
        self.progressBar.setGeometry(QtCore.QRect(65, 414, 155, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.mainPushButton = QtWidgets.QPushButton(DemoApp)
        self.mainPushButton.setGeometry(QtCore.QRect(230, 410, 120, 31))
        self.mainPushButton.setObjectName("mainPushButton")
        self.readConfigFilePushButton = QtWidgets.QPushButton(DemoApp)
        self.readConfigFilePushButton.setGeometry(QtCore.QRect(490, 410, 121, 31))
        self.readConfigFilePushButton.setObjectName("readConfigFilePushButton")
        self.writeConfigFilePushButton = QtWidgets.QPushButton(DemoApp)
        self.writeConfigFilePushButton.setGeometry(QtCore.QRect(620, 410, 121, 31))
        self.writeConfigFilePushButton.setObjectName("writeConfigFilePushButton")
        self.mainPushButton_2 = QtWidgets.QPushButton(DemoApp)
        self.mainPushButton_2.setGeometry(QtCore.QRect(360, 410, 120, 31))
        self.mainPushButton_2.setObjectName("mainPushButton_2")

        self.retranslateUi(DemoApp)
        self.tabWidget.setCurrentIndex(0)
        self.mainPushButton.clicked.connect(DemoApp.multiThread_runMainAnalysis)
        self.selectInputFolderPushButton.clicked.connect(DemoApp.showInputFolderDialog)
        self.selectOutputFolderPushButton.clicked.connect(DemoApp.showOutputFolderDialog)
        self.readConfigFilePushButton.clicked.connect(DemoApp.readConfigFileDialog)
        self.writeConfigFilePushButton.clicked.connect(DemoApp.writeConfigFileDialog)
        self.mainPushButton_2.clicked.connect(DemoApp.singleThread_runMainAnalysis)
        QtCore.QMetaObject.connectSlotsByName(DemoApp)

    def retranslateUi(self, DemoApp):
        _translate = QtCore.QCoreApplication.translate
        DemoApp.setWindowTitle(_translate("DemoApp", "DemoApp"))
        self.groupBox.setTitle(_translate("DemoApp", "ファイル関係"))
        self.outputFolderLineEdit.setText(_translate("DemoApp", "入力フォルダの絶対パスを指定してください"))
        self.inputFolderLineEdit.setText(_translate("DemoApp", "入力フォルダの絶対パスを指定してください"))
        self.label_2.setText(_translate("DemoApp", "出力フォルダ"))
        self.label_3.setText(_translate("DemoApp", "Configファイル"))
        self.configFileLineEdit.setText(_translate("DemoApp", "入力フォルダの絶対パスを指定してください"))
        self.label.setText(_translate("DemoApp", "入力フォルダ"))
        self.selectInputFolderPushButton.setText(_translate("DemoApp", "入力フォルダを指定"))
        self.selectOutputFolderPushButton.setText(_translate("DemoApp", "出力フォルダを指定"))
        self.groupBox_2.setTitle(_translate("DemoApp", "例外テスト用"))
        self.valueErrorCheckBox.setText(_translate("DemoApp", "ValueError"))
        self.fileNotFoundErrorCheckBox.setText(_translate("DemoApp", "FileNotFoundError"))
        self.permissionErrorCheckBox.setText(_translate("DemoApp", "PermissionError"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DemoApp", "Main処理"))
        self.analyzerStateLabel.setText(_translate("DemoApp", "待機中"))
        self.mainPushButton.setText(_translate("DemoApp", "実行(QThread)"))
        self.readConfigFilePushButton.setText(_translate("DemoApp", "Configから読込む"))
        self.writeConfigFilePushButton.setText(_translate("DemoApp", "Configへ書込む"))
        self.mainPushButton_2.setText(_translate("DemoApp", "実行(Single)"))

